"use client";
import { useEffect, useState } from "react";

const features = [
  ["01","One calm workspace","Plan tasks, run focus sessions, and review your progress without switching tools."],
  ["02","Focus that feels natural","Flexible sessions, gentle reminders, and smart breaks help you find your rhythm."],
  ["03","Progress you can see","Simple weekly insights turn completed work into momentum you can actually feel."],
];

export default function Home() {
  const [menuOpen,setMenuOpen]=useState(false); const [dark,setDark]=useState(true); const [faq,setFaq]=useState(0);
  useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light"},[dark]);
  return <main>
    <nav className="nav shell"><a className="brand" href="#top"><span>F</span>FocusFlow</a><button className="menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?"Close":"Menu"}</button><div className={`navlinks ${menuOpen?"open":""}`}><a href="#features">Features</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><button className="theme" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?"☀":"☾"}</button><a className="button small" href="#pricing">Start focusing</a></div></nav>
    <section className="hero shell" id="top"><div className="eyebrow"><i/>Productivity, without the pressure</div><h1>Make space for<br/><em>meaningful work.</em></h1><p>FocusFlow brings your tasks, focus sessions, and progress into one beautifully simple workspace.</p><div className="actions"><a className="button" href="#pricing">Start for free <b>↗</b></a><a className="quiet" href="#how">See how it works ↓</a></div>
      <div className="product"><div className="glow"/><div className="app"><aside><div className="appmark">F</div><div className="side">⌂<span>✓</span><span>◷</span><span>⌁</span></div><div className="avatar">AK</div></aside><div className="dash"><header><div><small>MONDAY, MAY 12</small><h2>Good morning, Alex.</h2></div><button>＋ Add task</button></header><div className="dashgrid"><section className="panel"><div className="ptitle"><b>Today</b><small>4 tasks</small></div>{[["✓","Review project brief","Client work","9:00"],["","Homepage concept","Focus block · 48 min","10:30"],["","Team check-in","Work","1:00"],["","Plan tomorrow","Personal","4:30"]].map((t,i)=><div className={`task ${i===0?"done":""} ${i===1?"active":""}`} key={t[1]}><i>{t[0]}</i><div><b>{t[1]}</b><small>{t[2]}</small></div><time>{t[3]}</time></div>)}</section><section className="panel focus"><div className="ptitle"><b>Focus session</b><small>Deep work</small></div><div className="ring"><div><strong>48:12</strong><small>minutes remaining</small></div></div><div className="controls"><button>Ⅱ</button><span>Homepage concept</span><button>×</button></div></section></div><div className="week"><div><span>This week</span><b>12h 40m focused</b></div><div className="bars">{[45,70,52,92,66,28,18].map((h,i)=><span key={i} style={{height:`${h}%`}} className={i===3?"hot":""}><small>{"MTWTFSS"[i]}</small></span>)}</div></div></div></div></div>
    </section>
    <section className="proof shell"><p>Built for people who care about their time</p><div><span>◆ NORTHSTAR</span><span>◉ CIRCLE</span><span>▲ vertex</span><span>✦ LUMEN</span><span>◫ FRAME</span></div></section>
    <section className="features shell" id="features"><div className="intro"><div><label>THE FOCUSFLOW DIFFERENCE</label><h2>Less busywork.<br/><em>More real work.</em></h2></div><p>Every detail is designed to reduce friction, quiet the noise, and help you spend your energy where it matters.</p></div><div className="featuregrid">{features.map(([n,t,p])=><article key={n}><span>{n}</span><div className={`art a${n}`}><i/><b/><em/></div><h3>{t}</h3><p>{p}</p></article>)}</div></section>
    <section className="workflow" id="how"><div className="shell workinner"><div><label>A BETTER DAILY RHYTHM</label><h2>From scattered<br/>to <em>in flow.</em></h2><p>Start your day with clarity. Choose what matters, protect time for it, and finish knowing you moved forward.</p></div><ol>{[["Choose your priorities","Turn a crowded list into a focused plan for today."],["Enter focus mode","Give one task your full attention with a calm timer."],["Reflect and reset","See what you accomplished and plan what comes next."]].map(([t,p],i)=><li key={t}><span>{i+1}</span><div><b>{t}</b><p>{p}</p></div></li>)}</ol></div></section>
    <section className="pricing shell" id="pricing"><label>SIMPLE PRICING</label><h2>Start small. <em>Stay focused.</em></h2><div className="price"><div><label>FOCUSFLOW PERSONAL</label><h3>$0 <small>/ forever</small></h3><p>Everything you need to build a calmer, more intentional workday.</p></div><ul><li>✓ Unlimited tasks and projects</li><li>✓ Focus timer and session history</li><li>✓ Weekly productivity insights</li><li>✓ All themes and preferences</li></ul><a className="button" href="mailto:hello@focusflow.example">Get started free <b>↗</b></a></div></section>
    <section className="faq shell"><div><label>QUESTIONS, ANSWERED</label><h2>A few things<br/>you might <em>wonder.</em></h2></div><div className="faqlist">{[["Is FocusFlow really free?","Yes. The personal plan includes every core feature with no trial period or credit card required."],["Does it work on mobile?","FocusFlow is designed to feel at home on desktop, tablet, and mobile screens."],["Can I import my existing tasks?","You can bring tasks in from common tools using a simple CSV import."]].map(([q,a],i)=><div className="faqitem" key={q}><button onClick={()=>setFaq(faq===i?-1:i)}><span>{q}</span><b>{faq===i?"−":"+"}</b></button>{faq===i&&<p>{a}</p>}</div>)}</div></section>
    <footer><div className="shell footer"><div><a className="brand" href="#top"><span>F</span>FocusFlow</a><p>Make space for meaningful work.</p></div><div className="footlinks"><a href="#features">Features</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="mailto:hello@focusflow.example">Contact</a></div><p className="copy">© 2026 FocusFlow</p></div></footer>
  </main>
}

